# Generated by Django 5.0.1 on 2024-01-29 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('nickname', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('like_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('posting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.posting')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('nickname', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('posting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.posting')),
            ],
        ),
    ]
