# Generated by Django 5.0.1 on 2024-01-30 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_rename_posting_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
