# Generated by Django 5.0.1 on 2024-01-30 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_rename_posts_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='password',
            field=models.CharField(default=None, max_length=4),
        ),
        migrations.AlterField(
            model_name='comment',
            name='posting_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='posting_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='board.post'),
        ),
    ]
