# Generated by Django 5.0.1 on 2024-01-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_post_password_alter_comment_posting_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='password',
            field=models.CharField(max_length=4),
        ),
    ]
