# Generated by Django 5.0.1 on 2024-01-31 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_alter_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='posting_id',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='posting_id',
            new_name='post_id',
        ),
    ]
